# Site settings
title: ALPACK
description: A technovation startup.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ALPACK
user_title: Light. Years ahead.
user_description: sobre que tipo de startup somos... desenvolvimento de software e tal
email: alpackstartup@gmail.com
twitter_username: twitter username
github_username:  ALPACK
gplus_username:  google plus username

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
