# Site settings
title: ALPACK
description: Site sobre o grupo ALPACK
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ALPACK
email: alpack@gmail.com
github_username: ALPACK

# Google-analytics
google-analytics:
  id: "UA-130696275-1"

exclude: ["package.json", "src", "node_modules"]
